### ISSUE TITLE
Fading between frames does not work when controlling a chaser via a fader

### ISSUE THREAD

**Issue by fourbytes** [mcallegari/qlcplus#813] opened 2016-03-01 00:00 UTC
As the title says, it works fine when controlling it with a button though.

To reproduce, set the fade in time for each frame in a chaser and use a fader to turn it on, it won't fade, just flashes, now using a button to activate it, it fades between frames.

**Comment by plugz** [comment] 2016-03-01 08:01
I don't understand "Fading between frames". Please post in the forum and attach an example workspace to help us understand what you mean.

Thank you.

**Comment by mcallegari** [comment] 2016-03-01 08:22
This is not a proper issue report and this area is mostly reserved to developers.

As plugz suggested, please use the forum and:
- describe in details the issue you're seeing
- describe what you expect
- attach a sample workspace and the exact steps to reproduce what you think the issue is
- report the QLC+ version you're using and on which OS you're running it

Closing this

**Closed by mcallegari** 2016-03-01 08:22 UTC
