### ISSUE TITLE
[v5.beta3] Popup / Modal `OK`-button misplaced

### ISSUE THREAD

**Issue by susnux** [mcallegari/qlcplus#1391] opened 2023-02-12 19:43 UTC
**Describe the bug**
For popups like the disclaimer of the "select 2d view perspective" modal the confimation button is misplaced outside the popup.

**To Reproduce**
1. Open QLCplus
2. See popover with misplaced button

**Expected behavior**
Button should be within the modal

**Screenshots**
![Screenshot_20230212_203406](https://user-images.githubusercontent.com/1855448/218333198-33d002c8-e10b-4e71-863a-004af37c2846.png)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - QLC+ Version 5 beta 3 (git 2023-02-04)
 - Hardware: Lenovo IdeaPad 5 (Ryzen 5 5500U, 1080p Display)
   - QLCplus console output `Pixel density: 6.21023 size: QSizeF(309, 174)`

**Additional context**
System locale is set to German that is why the modal title says "Haftungsausschluss" instead of "Disclaimer"

**Comment by mcallegari** [comment] 2023-02-13 17:30
This is a known issue caused by Qt 5.15.x
That's why the official AppImage is based on Qt 5.14.2.
At this moment I don't support tickets for non official builds, so unless you are a developer and you have a patch for this I'm sorry but I'm gonna close this.

**Closed** 2023-04-28 14:32 UTC
