### ISSUE TITLE
Cuelist crossfade briefly dips in brightness at start of crossfade

### ISSUE THREAD

**Issue by CarnivalBen** [mcallegari/qlcplus#1596] opened 2024-07-08 16:37 UTC
**Describe the bug**
When using a cuelist with infinite hold scenes, and the crossfade slider function, the brightness of the scenes being crossfaded briefly dips as the crossfade starts.

**To Reproduce**
1. Open QLC+ with a blank workspace.
2. Add a single Generic fixture.
3. Create a scene called "full on": fixture set to 100%
4. Create a scene called "off": fixture set to 0%
5. Create a chaser with the two scenes in the order above, with the hold set to infinite.
6. Go to Virtual Console and add a cuelist. In the properties, use the chaser from step 5, and set the side fader to Crossfade.
7. Switch to Operate mode.
8. Open Fixture monitor.
9. Click the play button on the cuelist.
10. The fixture monitor should show the DMX value at 255.
11. With the crossfade slider selected, press the DOWN arrow on your keyboard to nudge the slider down. (you can also drag with mouse or use an external input, but the down arrow is an easy way to consistently show the problem)
12. As you press DOWN, observe the DMX output, you'll see that very very briefly the value will drop to 037, and then immediately back to 252.

**Expected behavior**
The crossfade should be a smooth transition between the two scenes, but instead you have this this "blink" as you begin to crossfade. It doesn't look like much of a problem on the screen, but when you control multiple fixtures with the scene you can see quite a noticable "blink" in the lighting.

**Screenshots**
This problem is difficult to capture on a screenshot, so I recorded a video of it happening using my phone pointing at the computer monitor in slow motion. I then recorded my phone screen while I slowly played it back to make it even slower. I have uploaded the result of this to YouTube as an unlisted video which shows the problem: 

[https://youtu.be/PtYDBmUBcbo](https://youtu.be/PtYDBmUBcbo)

You can see the problem happen at 7 seconds into the video. Watch it closely, it drops to 037 and then quickly returns to 252.

**Desktop (please complete the following information):**
 - OS: Window 11
 - QLC+ Version: 4.13.1
 - High spec laptop.

**Comment by yestalgia** [comment] 2024-09-22 01:27
I've confirmed this issue on Window 11, 4.13.1 GIT. Very Strange.

**Comment by sbenejam** [comment] 2024-09-22 06:07
I just tested in Ubuntu 22.04 with 4.13.2-GIT works as expected.

Missatge de Lachlan Hicks ***@***.***> del dia dg., 22 de
set. 2024 a les 3:28:

**Comment by cmuellner** [comment] 2024-11-06 08:51
I can confirm this issue with 4.13.1 on Fedora 41.
It takes indeed a camera to spot the 037.

**Comment by mcallegari** [comment] 2024-11-06 11:03
Is this fixed with latest sources or not?

**Comment by cmuellner** [comment] 2024-11-06 12:43
I cannot reproduce with the latest git sources. But I also did not find the fix in the git log.

**Closed** 2024-12-03 19:22 UTC
