### ISSUE TITLE
The display of trusses and lamps cannot be seen in the 3D view under Win11

### ISSUE THREAD

**Issue by JiaminRen** [mcallegari/qlcplus#1591] opened 2024-07-01 06:16 UTC
![2161719814312_ pic_hd](https://github.com/mcallegari/qlcplus/assets/5237816/ed854b22-01ef-4023-ac32-d29366191372)
![2171719814383_ pic_hd](https://github.com/mcallegari/qlcplus/assets/5237816/70e1bca3-0c2d-48d7-8400-8489862cafad)
![2181719814563_ pic](https://github.com/mcallegari/qlcplus/assets/5237816/aea2e032-c6a6-4ef2-82d2-9f9564a8bea9)

**Comment by mcallegari** [comment] 2024-07-01 08:56
Duplicate of 
https://www.qlcplus.org/forum/viewtopic.php?t=16496
https://www.qlcplus.org/forum/viewtopic.php?t=16585

**Closed by mcallegari** 2024-07-01 08:56 UTC

**Comment by JiaminRen** [comment] 2024-07-02 07:06
If I want to debug 3d rendering for intel graphics, do you have any suggestions, since most laptops still have intel graphics?

**Comment by mcallegari** [comment] 2024-07-02 07:15
The only way to debug is to build from sources, understand the code, understand the GLSL shaders, use proper tools like RenderDoc and eventually fix the specific case.
