### ISSUE TITLE
Submaster not affecting Cue List in Solo Frame

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1466] opened 2023-10-25 07:07 UTC
Investigate the issue discussed here
https://www.qlcplus.org/forum/viewtopic.php?t=16731

**Comment by mcallegari** [comment] 2023-10-28 10:58
For some reason this seems to be related to value == 0 only.
Not easy at all to be solved.

**Comment by kpr0th** [comment] 2023-12-29 05:23
I did some spelunking and figured out why this is happening.  
- When each chaser step starts, ChaserRunner::startNewStep() calls Function::requestAttributeOverride(Function::Intensity, 0*1).  
- Function::requestAttributeOverride sets up a new "AttributeOverride" struct and defaults m_value to 0.0, and then calls adjustAttribute(0, attributeID).
- This runs Chaser::adjustAttribute, which in turn calls Function::adjustAttribute to fetch an attrIndex.  If the attrIndex is "Intensity" it finishes by calling getAttributeValue and overrides the step intensity or m_startupAction.m_masterIntensity accordingly. But if attrIndex is != Intensity, it skips that logic.
- Function::adjustAttribute returns a -1 if either the overrideMap doesn't contain the requested attribute, *or* if overrideMap[attributeId].m_value == the "new" value.

So, the problem is that this m_value field is initialized to 0.0, and then the override logic is skipped because it's trying to override to a 0.

If I change line 1269 in function.cpp to this: override.m_value = **-1.0**
Then this specific issue is fixed.  BUT, I have no idea what other ramifications this change would have.

Alternatively, I think it could be fixed by adding logic into Function::adjustAttribute() to bypass the short-circuiting logic if it's handling an "Intensity" attribute, and allow value="0" to be processed, even if m_value==value is true.

Hopefully this helps in tracking down a possible fix for this issue.

**Comment by mcallegari** [comment] 2023-12-30 10:06
@kpr0th thanks for the investigation!
A fix that makes sense to me is changing the following line in `Function::adjustAttribute`
```
if (m_overrideMap.contains(attributeId) == false || m_overrideMap[attributeId].m_value == value)
    return -1;
```
to
```
if (m_overrideMap.contains(attributeId) == false)
    return -1;
```
In the end overriding means the caller wants its own intensity factor.
What do you think?
I tested the change above and it seems to work as expected to me.

**Comment by kpr0th** [comment] 2023-12-30 15:18
You're welcome.

That change makes total sense to me.  Accomplishes pretty much the same thing as my first suggestion, without changing the "default" m_value setting.

**Closed** 2024-01-01 17:43 UTC
Labels: issue confirmed
