### ISSUE TITLE
Not Responding to External OSC input

### ISSUE THREAD

**Issue by donert** [mcallegari/qlcplus#715] opened 2015-12-13 00:04 UTC
I am trying to get TouchOSC working with the OSC plugin. 
The problem I am encountering is getting a QLC button to fire when sent an OSC command.
I am sure I have all of the network configuration working.
This screen shot shows that packets are being received - the count increments whenever I hit a button on TouchOSC.
￼￼
![screen shot 2015-12-12 at 6 45 56 pm](https://cloud.githubusercontent.com/assets/13247714/11764495/bc1bba3a-a100-11e5-9c79-a86221c93e36.png)

I figure that count is being incremented by OSCController::processPendingPackets, line 388.

I have a button configured to receive the message:
![screen shot 2015-12-12 at 6 42 43 pm](https://cloud.githubusercontent.com/assets/13247714/11764499/ec91f2c4-a100-11e5-959f-3a2a27c76e61.png)

I have verified that "/2/toggle2" is being transmitted via another program. I haven't figure out what the "50239" is. Is it the hash?

No specific messages are showing up in the debug output ... but all of the qDebug lines in the key method are commented out.

I am seeing some universe error messages in the debug output, but don't know if it is relevant or not.

./qlcplus -d

Q Light Controller Plus version 4.10.1
This program is licensed under the terms of the Apache 2.0 license.
Copyright (c) Heikki Junnila (hjunnila@users.sf.net)
Copyright (c) Massimo Callegari (massimocallegari@yahoo.it)

bool QLCFixtureDefCache::loadMap(const QDir &) Unknown Fixture Map tag:  "FixturesMap"
bool QLCFixtureDefCache::loadMap(const QDir &) Unknown Fixture Map tag:  ""
void IOPluginCache::load(const QDir &) "libolaio.dylib" doesn't contain an I/O plugin: "Cannot load library /Applications/QLC+.app/Contents/PlugIns/libolaio.dylib: (dlopen(/Applications/QLC+.app/Contents/PlugIns/libolaio.dylib, 5): Library not loaded: /opt/local/lib/libolaserver.0.dylib\n  Referenced from: /Applications/QLC+.app/Contents/PlugIns/libolaio.dylib\n  Reason: image not found)"
libpng warning: iCCP: known incorrect sRGB profile
InputPatch *InputOutputMap::inputPatch(quint32) const Universe 5 out of bounds.
OutputPatch *InputOutputMap::outputPatch(quint32) const Universe 5 out of bounds.
OutputPatch *InputOutputMap::feedbackPatch(quint32) const Universe 5 out of bounds.

**Comment by plugz** [comment] 2015-12-13 10:49
Hello,

- What is the program sending OSC ?
- What type of OSC messages is it sending ? (int or float or whatever)
- Is the joystick icon showing when you send OSC messages to QLC+ ?

**Comment by mcallegari** [comment] 2015-12-13 11:04
@donert This area is quite reserved to developers or topics strictly related to the QLC+ development (sources, build issues, patches, etc.)

Yours is a generic technical support request, which should be done in the QLC+ forums like everybody else does: http://www.qlcplus.org/forum/
By the way, the problem seems to be on Universe 5. To have it you need to load a workspace with 5 universes, otherwise, by default, QLC+ will expose just 4 universes.

Please write in the forum all the details needed to understand what you're trying to do, including:
- OS version
- QLC+ version
- what is exactly the issue and the steps to reproduce it
- attach your workspace so we can see how your IO is configured

**Comment by donert** [comment] 2015-12-15 14:58
@plugz as Massimo has requested I will open up a discussion topic in the forum and answer your questions there.

**Comment by plugz** [comment] 2015-12-18 12:41
Discussion is here: http://qlcplus.org/forum/viewtopic.php?f=5&t=9303

Closing this issue

**Closed by plugz** 2015-12-18 12:41 UTC
