### ISSUE TITLE
Channel modifiers have stop to work for inverted RGB channels

### ISSUE THREAD

**Issue by Tolmino** [mcallegari/qlcplus#644] opened 2015-11-02 16:57 UTC
Hi, after that commit
https://github.com/mcallegari/qlcplus/commit/30ca3f514aa62fd83b06141bd34817b92316b904
i cannot use all machines that have RGB channels with channel modifiers set to "invert" 
them have stop to do right colors.

i have made a video where is present the issue
http://www.tolmino.it/onnik/VID-20151102-WA0015.mp4

**Comment by janosvitok** [comment] 2015-11-02 17:07
Tolmino, can you please post somewhere your qxw file?

**Comment by Tolmino** [comment] 2015-11-02 17:08
here:
http://www.tolmino.it/onnik/TOUR_2014_con_Midi_no_peperoni_input.qxw

**Comment by Tolmino** [comment] 2015-11-02 17:09
the devices are Mini Wash Led 3W

**Comment by janosvitok** [comment] 2015-11-03 07:37
The problem here is caused by slider 59 and 60. If you pull them down, the colors are OK.
Somehow the slider emit their values even in design mode.

Another problem found is that simple desk shows values *after* modifiers, while it should before modifiers and maybe also before GM.

**Comment by Tolmino** [comment] 2015-11-04 20:47
Jano, can you simple revert ?

**Comment by janosvitok** [comment] 2015-11-04 21:06
Tolmino,
I don't think that commit is problem. So far I believe the commit is correct.

The problem you see (255 210 000) is caused by your slider 59 (controlling green channels, at 45 = 255-210) and slider 60 (blue channels, at 255 = 255 - 0) -AND- the fact that sliders send their value even in design mode (which is not caused by my commit, but seems it's been there for a longer time).

So: to fix your color buttons, just pull down both sliders to zero in operate mode, and you'll be fine.

Please comment whether that helps or not.

**Comment by Tolmino** [comment] 2015-11-05 16:33
Right Jano.... we don't see that sliders because anybody has add them when light designer wasn't working.

**Comment by janosvitok** [comment] 2015-11-05 20:59
Can we close this issue then?

**Comment by thedima1997** [comment] 2015-11-05 21:33
Yes, you can

**Closed** 2015-11-08 21:46 UTC
Labels: in progress, issue confirmed
