### ISSUE TITLE
Flash function not working on LTP channels

### ISSUE THREAD

**Issue by lcslouis** [mcallegari/qlcplus#23] opened 2013-01-03 06:14 UTC
the flash function isn't working as expected it only works properly during chases

if i want to flash a fixture lets say from its off position to another value this is a chauvet color pallet the flash should  flash the scene then revert to active or previous values but this only applies during a chaser. flash should be

on button down hold-  values should be what scene is programmed for that flash
on button release - values should return to previous 

hope this explanation explains it.

**Comment by mcallegari** [comment] 2015-02-28 12:20
OK, I renamed this and investigated the issue, since it seems to be the hottest topic these days :confounded: 

For the devs:
When a Scene is started, the Scene::write(MasterTimer* timer, QList<Universe*> ua) method is called by MasterTimer every tick.
The issue is that HTP channels are persistant, while LTP aren't. Once LTP channels reach their target value, they are removed from the Scene m_fader. So basically at the next tick, m_fader does nothing.
This is where is happens:
https://github.com/mcallegari/qlcplus/blob/master/engine/src/genericfader.cpp#L106

When another Function flashes, there is no memory of the previous value of a LTP channel, so when flashing is done, the channel remains to the last value set.

I haven't found a clean solution yet, but at least I have a clear picture of what is happening.

**Comment by mcallegari** [comment] 2015-02-28 13:02
Should be finally fixed by https://github.com/mcallegari/qlcplus/commit/829bb9384399b685a890e10ec6c5b052eda71452

**Comment by joedemax** [comment] 2015-02-28 17:00
Most flexible way to do something like this is to provide the option to solo frames over each other. So for example, one frame could be set to solo over another, so when a button in that frame was pressed, it would turn off all buttons in the other frame until it was released at which point it would go back to the previous scene.

**Closed** 2015-03-15 10:34 UTC
