### ISSUE TITLE
Update build system to CMake

### ISSUE THREAD

**Issue by yestalgia** [mcallegari/qlcplus#1408] opened 2023-03-21 14:43 UTC
[cmake ](https://cmake.org/)is recommended for Qt 6 and QLC+ hasn't switched to it yet. 

There's a pretty bad PR that was supposed to evolve but got closed which included porting to cmake:

- https://github.com/mcallegari/qlcplus/pull/1214

It could take quite a bit of work but the following resources should help:

- https://wiki.qt.io/CMake_Port/Porting_Guide
- https://pypi.org/project/qmake2cmake/

The TODO list is the following:

- [x] Qt5 v4 build on Linux
- [x] Qt5 v4 test units on Linux (make check)
- [x] Qt5 v4 deploy on Linux (.deb package)
- [x] Qt5 v5 build on Linux
- [ ] Qt6 v4 build on Linux
- [x] Qt5 v5 deploy on Linux (appimage package)
- [x] Qt5 v4 build on Windows
- [ ] Qt6 v4 build on Windows
- [x] Qt5 v4 deploy on Windows (.exe bundle)
- [x] Qt5 v5 build on Windows
- [x] Qt5 v5 deploy on Windows (.exe bundle)
- [ ] Qt5 v4 build on macOS
- [ ] Qt6 v4 build on macOS
- [ ] Qt5 v4 deploy on macOS (.dmg bundle)
- [ ] Qt5 v5 build on macOS
- [ ] Qt5 v5 deploy on macOS (.dmg bundle)
- [x] Coverage build

**Comment by yestalgia** [comment] 2023-03-21 14:45
@Itay-Lifshitz
Please record your progress here.

**Comment by Itay-Lifshitz** [comment] 2023-03-29 02:55
@mcallegari 
I compiled the GUI program of QLC++4 using Qt5 + MSVC 2017 + CMake.
But when I tried to compile test projects, I got some troubles.
For instance, in the ui/test/aboutbox/aboutbox_test.cpp file, we have the following code block.
`
#define private public
#include "aboutbox.h"
#undef protected
`
And then it accesses the original private function of AboutBox class like the following code.
`
void AboutBox_Test::slotTimeout()
{
    AboutBox ab(NULL);
    ab.m_timer->stop();

    QCOMPARE(ab.m_row, -1);
    QCOMPARE(ab.m_increment, 1);

    for (int i = 0; i <= CONTRIBCOUNT; i++)
    {
        ab.slotTimeout();
        QCOMPARE(ab.m_row, i);
        QCOMPARE(ab.m_increment, 1);
    }

    for (int i = CONTRIBCOUNT - 1; i > 0; i--)
    {
        ab.slotTimeout();
        QCOMPARE(ab.m_row, i);
        QCOMPARE(ab.m_increment, -1);
    }
}
`

Now the problem is, the slotTimeout() function of AboutBox is originally private, and in the test project it pretends to be public.
So when compiling the aboutbox_test project, it throws the following LINK error.
`
1>aboutbox_test.obj : error LNK2019: unresolved external symbol "public: void __cdecl AboutBox::slotTimeout(void)" (?slotTimeout@AboutBox@@QEAAXXZ) referenced in function "private: void __cdecl AboutBox_Test::slotTimeout(void)" (?slotTimeout@AboutBox_Test@@AEAAXXZ)
1>aboutbox_test.obj : error LNK2019: unresolved external symbol "public: void __cdecl AboutBox::slotItemClicked(void)" (?slotItemClicked@AboutBox@@QEAAXXZ) referenced in function "private: void __cdecl AboutBox_Test::itemClick(void)" (?itemClick@AboutBox_Test@@AEAAXXZ)
1>E:\Project\C\qlcplus\Itay\build\ui\test\aboutbox\Debug\aboutbox_test.exe : fatal error LNK1120: 2 unresolved externals
`

**Comment by mcallegari** [comment] 2023-03-29 07:15
Is the cmake build with GCC working?
I really have no idea how to support you on MSVC as I have never used it and never needed it to be supported.
I think you can try your luck on Qt forums or with Google.
For example here they suggest to use MSVC 2019 for Qt 5.15:
https://musescore.org/it/handbook/developers-handbook/compilation/compile-instructions-windows-visual-studio/compile

**Comment by Itay-Lifshitz** [comment] 2023-03-30 16:31
@mcallegari 
I am wondering if the plugin/udmx is supported in Windows.
It uses <libusb.h> in 2 cpp files, but <libusb.h> seems not to be in Windows OS.
So It occurs compile error like 
"fatal error: libusb.h: No such file or directory".
Do we need to compile udmx in Windows? If so, how do we handle this libusb in Windows?

**Comment by Itay-Lifshitz** [comment] 2023-03-31 01:39
@mcallegari 
I tried to compile QLC++5 using MinGW + Qt5.12 and got compile error.
In the engine\src\scriptrunner.cpp:67, it calls setInterrupted function of the class QJSEngine.
But according to the following [reference](https://doc.qt.io/qt-5/qjsengine.html#setInterrupted), this function was introduced in Qt 5.14.
So the minimum required version of Qt to compile QLC++5 with QML should be 5.14, not 5.10 as mentioned in [QLC-Plus-5-build-HOWTO](https://github.com/mcallegari/qlcplus/wiki/QLC-Plus-5-build-HOWTO)

**Comment by mcallegari** [comment] 2023-03-31 07:06
Fixed.
I don't really understand why you went back to Qt 5.12 which is now ancient and outdated.

**Comment by Itay-Lifshitz** [comment] 2023-03-31 07:22
@mcallegari  
Cause I downloaded qt5 from [here](https://www.qt.io/offline-installers)
I didn't want to download the source code of Qt and compile it.
Maybe it could be kind of a stupid question, but can you kindly guide me on where can I download the offline installer for the latest version of Qt5 and Qt6?
Thanks in advance.

**Comment by Itay-Lifshitz** [comment] 2023-04-01 12:37
@mcallegari 
Can you kindly guide me how I can install full version of Qt6 without commercial license from this [official link](https://www.qt.io/download-open-source)
Do I really need to download the source code and compile it?

**Comment by mcallegari** [comment] 2023-04-01 12:40
You need to use the online installer. That's the only way to download Qt libraries nowadays.
No need to build from sources.

**Comment by Itay-Lifshitz** [comment] 2023-04-01 15:31
@mcallegari 
After I succesfully build project with CMake, do I need to update appveyor.yml using CMake as well?

**Comment by mcallegari** [comment] 2023-04-02 09:26
I can take care of it

**Comment by mcallegari** [comment] 2023-11-05 09:05
@Itay-Lifshitz there's still an issue with cmake port on Windows.
The udmx plugin is not linking libusb-1.0 DLL, so it's not recognized as a valid plugin at boot.
I tried to fix this myself but no luck. Can you please have a look? Thanks

**Comment by Itay-Lifshitz** [comment] 2023-11-05 10:16
> @Itay-Lifshitz there's still an issue with cmake port on Windows. The udmx plugin is not linking libusb-1.0 DLL, so it's not recognized as a valid plugin at startup. I tried to fix this myself but no luck. Can you please have a look? Thanks

I checked it and looks like has no problem.
Can you please tell me how I can see that "the udmx plugin is not recognized as a valid plugin at startup"?

**Comment by mcallegari** [comment] 2023-11-05 10:24
I see this
`void IOPluginCache::load(const QDir&) "udmx.dll" doesn't contain an I/O plugin: "Failed to extract plugin meta data from 'C:/qlcplus/Plugins/udmx.dll'"
`and also I checked the DLL dependency and it looks like this
```
 objdump.exe -p Plugins/udmx.dll | grep DLL
        DLL
 vma:            Hint    Time      Forward  DLL       First
        DLL Name: libgcc_s_dw2-1.dll
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: libstdc++-6.dll
        DLL Name: Qt5Core.dll
```
In the qmake version there was also `libusb-1.0.dll` in the dependencies

**Comment by Itay-Lifshitz** [comment] 2023-11-05 12:09
In the plugins/udmx/src/libusb_dyn.c file I found some hardcoded filename.
`
#define LIBUSB_DLL_NAME TEXT("libusb0.dll")
`
And it probably needs to be replaced with "libusb-1.0.dll".
What do you think? @mcallegari

**Comment by mcallegari** [comment] 2023-11-05 12:55
That's a good point but those files are no longer used. In fact you can safely remove them from build (I tried) and nothing will change. Those were dropper in favour of the more standard libusb 1.0. That's why it's important to link it to the final DLL.
I built again the qmake version and I confirm that libusb-1.0 is correctly linked.

```
$ objdump.exe -p src/udmx.dll | grep DLL
        DLL
 vma:            Hint    Time      Forward  DLL       First
        DLL Name: libgcc_s_dw2-1.dll
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: libstdc++-6.dll
        DLL Name: libusb-1.0.dll
        DLL Name: Qt5Core.dll
        DLL Name: Qt5Widgets.dll
```

**Comment by Itay-Lifshitz** [comment] 2023-11-05 13:17
@mcallegari I opened PR, please check it and merge it.
You can probably get rid of the old libusb_dyn.c by yourself since I am not clear where it was used.

**Comment by mcallegari** [comment] 2023-11-05 13:20
@Itay-Lifshitz sorry we made the change at the same time.
I think your last comment led me to find the issue which was a wrong if/else:
https://github.com/mcallegari/qlcplus/blob/44a9dd3213a6580241677e598e93517e9f0ecdeb/plugins/udmx/src/CMakeLists.txt#L41

See 5ba3e34543ea8f57f181eb3e994f0de88223e4a7

**Comment by Itay-Lifshitz** [comment] 2023-11-05 13:23
@mcallegari Looks like udmx.cpp is still missing from CMakeList.txt
You can add it on your side.

**Comment by mcallegari** [comment] 2023-11-05 13:30
> @mcallegari Looks like udmx.cpp is still missing from CMakeList.txt You can add it on your side.

It's here
https://github.com/mcallegari/qlcplus/blob/master/plugins/udmx/src/CMakeLists.txt#L41

**Comment by mcallegari** [comment] 2024-02-05 18:17
Let's close this.
Eventually I will open a new one specific for macOS or Qt6

**Closed by mcallegari** 2024-02-05 18:17 UTC
